/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xadrez;

import xadrez.boardgame.Board;
import xadrez.chess.ChessMatch;

public class App {
    public static void main(String[] args) {
        ChessMatch chessMatch = new ChessMatch();
        UI.printBoard(chessMatch.getPieces());
    }
}
