/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xadrez;

import xadrez.boardgame.Board;

public class App {
    public static void main(String[] args) {
        Board board = new Board(8, 8);
    }
}
